CREATE TABLE `images_images` (
  `id` mediumint(15) NOT NULL AUTO_INCREMENT,
  `fieldid` mediumint(15) NOT NULL DEFAULT '0',
  `uid` int(11) NOT NULL DEFAULT '0',
  `hash` varchar(16) NOT NULL DEFAULT '',
  `field` varchar(64) NOT NULL DEFAULT '',
  `type` enum('jpg','png','gif','ascii-small','ascii-medium','ascii-large','unknown') NOT NULL DEFAULT 'unknown',
  `storage` enum('files','database') NOT NULL DEFAULT 'files',
  `blacklisted` enum('none','temporary','permanent') NOT NULL DEFAULT 'none',
  `md5` varchar(32) NOT NULL DEFAULT '',
  `url` varchar(255) NOT NULL DEFAULT '',
  `width` int(11) NOT NULL DEFAULT '0',
  `height` int(11) NOT NULL DEFAULT '0',
  `bytes` int(11) NOT NULL DEFAULT '0',
  `views` int(11) NOT NULL DEFAULT '0',
  `updates` int(11) NOT NULL DEFAULT '0',
  `errors` int(11) NOT NULL DEFAULT '0',
  `megabytes` float(26,12) NOT NULL DEFAULT '0',
  `views_hourly` int(11) NOT NULL DEFAULT '0',
  `images_hourly` int(11) NOT NULL DEFAULT '0',
  `errors_hourly` int(11) NOT NULL DEFAULT '0',
  `megabytes_hourly` float(26,12) NOT NULL DEFAULT '0',
  `views_daily` int(11) NOT NULL DEFAULT '0',
  `images_daily` int(11) NOT NULL DEFAULT '0',
  `errors_daily` int(11) NOT NULL DEFAULT '0',
  `megabytes_daily` float(26,12) NOT NULL DEFAULT '0',
  `views_weekly` int(11) NOT NULL DEFAULT '0',
  `images_weekly` int(11) NOT NULL DEFAULT '0',
  `errors_weekly` int(11) NOT NULL DEFAULT '0',
  `megabytes_weekly` float(26,12) NOT NULL DEFAULT '0',
  `views_biweekly` int(11) NOT NULL DEFAULT '0',
  `images_biweekly` int(11) NOT NULL DEFAULT '0',
  `errors_biweekly` int(11) NOT NULL DEFAULT '0',
  `megabytes_biweekly` float(26,12) NOT NULL DEFAULT '0',
  `views_monthly` int(11) NOT NULL DEFAULT '0',
  `images_monthly` int(11) NOT NULL DEFAULT '0',
  `errors_monthly` int(11) NOT NULL DEFAULT '0',
  `megabytes_monthly` float(26,12) NOT NULL DEFAULT '0',
  `views_quarterly` int(11) NOT NULL DEFAULT '0',
  `images_quarterly` int(11) NOT NULL DEFAULT '0',
  `errors_quarterly` int(11) NOT NULL DEFAULT '0',
  `megabytes_quarterly` float(26,12) NOT NULL DEFAULT '0',
  `views_yearly` int(11) NOT NULL DEFAULT '0',
  `images_yearly` int(11) NOT NULL DEFAULT '0',
  `errors_yearly` int(11) NOT NULL DEFAULT '0',
  `megabytes_yearly` float(26,12) NOT NULL DEFAULT '0',
  `start_hourly` int(11) NOT NULL DEFAULT '0',
  `ended_hourly` int(11) NOT NULL DEFAULT '0',
  `start_daily` int(11) NOT NULL DEFAULT '0',
  `ended_daily` int(11) NOT NULL DEFAULT '0',
  `start_weekly` int(11) NOT NULL DEFAULT '0',
  `ended_weekly` int(11) NOT NULL DEFAULT '0',
  `start_biweekly` int(11) NOT NULL DEFAULT '0',
  `ended_biweekly` int(11) NOT NULL DEFAULT '0',
  `start_monthly` int(11) NOT NULL DEFAULT '0',
  `ended_monthly` int(11) NOT NULL DEFAULT '0',
  `start_quarterly` int(11) NOT NULL DEFAULT '0',
  `ended_quarterly` int(11) NOT NULL DEFAULT '0',
  `start_yearly` int(11) NOT NULL DEFAULT '0',
  `ended_yearly` int(11) NOT NULL DEFAULT '0',
  `viewed` int(11) NOT NULL DEFAULT '0',
  `updated` int(11) NOT NULL DEFAULT '0',
  `created` int(11) NOT NULL DEFAULT '0',
  `checked` int(11) NOT NULL DEFAULT '0',
  `errored` int(11) NOT NULL DEFAULT '0',
  `emailed` int(11) NOT NULL DEFAULT '0',
  `data` LONGTEXT,
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`hash`,`uid`,`field`,`md5`,`checked`,`url`,`emailed`),
  KEY `PERIODIC` (`ended_yearly`,`start_yearly`,`ended_quarterly`,`start_quarterly`,`ended_monthly`,`start_monthly`,`start_hourly`,`ended_hourly`,`start_daily`,`ended_daily`,`start_weekly`,`ended_weekly`,`start_biweekly`,`ended_biweekly`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `images_fields` (
  `id` mediumint(15) NOT NULL AUTO_INCREMENT,
  `hash` varchar(16) NOT NULL DEFAULT '',
  `field` varchar(64) NOT NULL DEFAULT '',
  `typal` enum('icons','logo','photo','avatar','unknown') NOT NULL DEFAULT 'unknown',
  `views` int(11) NOT NULL DEFAULT '0',
  `images` int(11) NOT NULL DEFAULT '0',
  `errors` int(11) NOT NULL DEFAULT '0',
  `megabytes` float(26,12) NOT NULL DEFAULT '0',
  `views_hourly` int(11) NOT NULL DEFAULT '0',
  `images_hourly` int(11) NOT NULL DEFAULT '0',
  `errors_hourly` int(11) NOT NULL DEFAULT '0',
  `megabytes_hourly` float(26,12) NOT NULL DEFAULT '0',
  `views_daily` int(11) NOT NULL DEFAULT '0',
  `images_daily` int(11) NOT NULL DEFAULT '0',
  `errors_daily` int(11) NOT NULL DEFAULT '0',
  `megabytes_daily` float(26,12) NOT NULL DEFAULT '0',
  `views_weekly` int(11) NOT NULL DEFAULT '0',
  `images_weekly` int(11) NOT NULL DEFAULT '0',
  `errors_weekly` int(11) NOT NULL DEFAULT '0',
  `megabytes_weekly` float(26,12) NOT NULL DEFAULT '0',
  `views_biweekly` int(11) NOT NULL DEFAULT '0',
  `images_biweekly` int(11) NOT NULL DEFAULT '0',
  `errors_biweekly` int(11) NOT NULL DEFAULT '0',
  `megabytes_biweekly` float(26,12) NOT NULL DEFAULT '0',
  `views_monthly` int(11) NOT NULL DEFAULT '0',
  `images_monthly` int(11) NOT NULL DEFAULT '0',
  `errors_monthly` int(11) NOT NULL DEFAULT '0',
  `megabytes_monthly` float(26,12) NOT NULL DEFAULT '0',
  `views_quarterly` int(11) NOT NULL DEFAULT '0',
  `images_quarterly` int(11) NOT NULL DEFAULT '0',
  `errors_quarterly` int(11) NOT NULL DEFAULT '0',
  `megabytes_quarterly` float(26,12) NOT NULL DEFAULT '0',
  `views_yearly` int(11) NOT NULL DEFAULT '0',
  `images_yearly` int(11) NOT NULL DEFAULT '0',
  `errors_yearly` int(11) NOT NULL DEFAULT '0',
  `megabytes_yearly` float(26,12) NOT NULL DEFAULT '0',
  `start_hourly` int(11) NOT NULL DEFAULT '0',
  `ended_hourly` int(11) NOT NULL DEFAULT '0',
  `start_daily` int(11) NOT NULL DEFAULT '0',
  `ended_daily` int(11) NOT NULL DEFAULT '0',
  `start_weekly` int(11) NOT NULL DEFAULT '0',
  `ended_weekly` int(11) NOT NULL DEFAULT '0',
  `start_biweekly` int(11) NOT NULL DEFAULT '0',
  `ended_biweekly` int(11) NOT NULL DEFAULT '0',
  `start_monthly` int(11) NOT NULL DEFAULT '0',
  `ended_monthly` int(11) NOT NULL DEFAULT '0',
  `start_quarterly` int(11) NOT NULL DEFAULT '0',
  `ended_quarterly` int(11) NOT NULL DEFAULT '0',
  `start_yearly` int(11) NOT NULL DEFAULT '0',
  `ended_yearly` int(11) NOT NULL DEFAULT '0',
  `viewed` int(11) NOT NULL DEFAULT '0',
  `created` int(11) NOT NULL DEFAULT '0',
  `errored` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`hash`,`field`,`typal`),
  KEY `PERIODIC` (`ended_yearly`,`start_yearly`,`ended_quarterly`,`start_quarterly`,`ended_monthly`,`start_monthly`,`start_hourly`,`ended_hourly`,`start_daily`,`ended_daily`,`start_weekly`,`ended_weekly`,`start_biweekly`,`ended_biweekly`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `images_errors` (
  `id` mediumint(15) NOT NULL AUTO_INCREMENT,
  `type` enum('system','module','user','unknown') NOT NULL DEFAULT 'unknown',
  `uid` int(11) NOT NULL DEFAULT '0',
  `imageid` mediumint(15) NOT NULL DEFAULT '0',
  `fieldid` mediumint(15) NOT NULL DEFAULT '0',
  `code` varchar(64) NOT NULL DEFAULT '',
  `when` int(11) NOT NULL DEFAULT '0',
  `message` varchar(255),
  `emailed` int(11) NOT NULL DEFAULT '0',
  `created` int(11) NOT NULL DEFAULT '0',
  `deleted` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`type`,`uid`,`imageid`,`fieldid`,`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `images_statistics` (
  `id` mediumint(32) NOT NULL AUTO_INCREMENT,
  `mode` enum('hourly','daily','weekly','biweekly','monthly','quarterly','yearly') NOT NULL DEFAULT '',
  `typal` enum('icons','logo','photo','avatar') NOT NULL DEFAULT '',
  `type` enum('fields','images') NOT NULL DEFAULT '',
  `typeid` mediumint(15) NOT NULL DEFAULT '0',
  `hash` varchar(18) NOT NULL DEFAULT '',
  `key` varchar(64) NOT NULL DEFAULT '',
  `timezone` enum('Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Asmera', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Timbuktu', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'America/Anguilla', 'America/Antigua', 'America/Araguaina', 'America/Argentina/Buenos_Aires', 'America/Argentina/Catamarca', 'America/Argentina/ComodRivadavia', 'America/Argentina/Cordoba', 'America/Argentina/Jujuy', 'America/Argentina/La_Rioja', 'America/Argentina/Mendoza', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Aruba', 'America/Asuncion', 'America/Atikokan', 'America/Atka', 'America/Bahia', 'America/Bahia_Banderas', 'America/Barbados', 'America/Belem', 'America/Belize', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Bogota', 'America/Boise', 'America/Buenos_Aires', 'America/Cambridge_Bay', 'America/Campo_Grande', 'America/Cancun', 'America/Caracas', 'America/Catamarca', 'America/Cayenne', 'America/Cayman', 'America/Chicago', 'America/Chihuahua', 'America/Coral_Harbour', 'America/Cordoba', 'America/Costa_Rica', 'America/Creston', 'America/Cuiaba', 'America/Curacao', 'America/Danmarkshavn', 'America/Dawson', 'America/Dawson_Creek', 'America/Denver', 'America/Detroit', 'America/Dominica', 'America/Edmonton', 'America/Eirunepe', 'America/El_Salvador', 'America/Ensenada', 'America/Fort_Wayne', 'America/Fortaleza', 'America/Glace_Bay', 'America/Godthab', 'America/Goose_Bay', 'America/Grand_Turk', 'America/Grenada', 'America/Guadeloupe', 'America/Guatemala', 'America/Guayaquil', 'America/Guyana', 'America/Halifax', 'America/Havana', 'America/Hermosillo', 'America/Indiana/Indianapolis', 'America/Indiana/Knox', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Tell_City', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Indianapolis', 'America/Inuvik', 'America/Iqaluit', 'America/Jamaica', 'America/Jujuy', 'America/Juneau', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Knox_IN', 'America/Kralendijk', 'America/La_Paz', 'America/Lima', 'America/Los_Angeles', 'America/Louisville', 'America/Lower_Princes', 'America/Maceio', 'America/Managua', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Matamoros', 'America/Mazatlan', 'America/Mendoza', 'America/Menominee', 'America/Merida', 'America/Metlakatla', 'America/Mexico_City', 'America/Miquelon', 'America/Moncton', 'America/Monterrey', 'America/Montevideo', 'America/Montreal', 'America/Montserrat', 'America/Nassau', 'America/New_York', 'America/Nipigon', 'America/Nome', 'America/Noronha', 'America/North_Dakota/Beulah', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/Ojinaga', 'America/Panama', 'America/Pangnirtung', 'America/Paramaribo', 'America/Phoenix', 'America/Port-au-Prince', 'America/Port_of_Spain', 'America/Porto_Acre', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Rainy_River', 'America/Rankin_Inlet', 'America/Recife', 'America/Regina', 'America/Resolute', 'America/Rio_Branco', 'America/Rosario', 'America/Santa_Isabel', 'America/Santarem', 'America/Santiago', 'America/Santo_Domingo', 'America/Sao_Paulo', 'America/Scoresbysund', 'America/Shiprock', 'America/Sitka', 'America/St_Barthelemy', 'America/St_Johns', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Thomas', 'America/St_Vincent', 'America/Swift_Current', 'America/Tegucigalpa', 'America/Thule', 'America/Thunder_Bay', 'America/Tijuana', 'America/Toronto', 'America/Tortola', 'America/Vancouver', 'America/Virgin', 'America/Whitehorse', 'America/Winnipeg', 'America/Yakutat', 'America/Yellowknife', 'Antarctica/Casey', 'Antarctica/Davis', 'Antarctica/DumontDUrville', 'Antarctica/Macquarie', 'Antarctica/Mawson', 'Antarctica/McMurdo', 'Antarctica/Palmer', 'Antarctica/Rothera', 'Antarctica/South_Pole', 'Antarctica/Syowa', 'Antarctica/Vostok', 'Arctic/Longyearbyen', 'Asia/Aden', 'Asia/Almaty', 'Asia/Amman', 'Asia/Anadyr', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Ashkhabad', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Baku', 'Asia/Bangkok', 'Asia/Beirut', 'Asia/Bishkek', 'Asia/Brunei', 'Asia/Calcutta', 'Asia/Choibalsan', 'Asia/Chongqing', 'Asia/Chungking', 'Asia/Colombo', 'Asia/Dacca', 'Asia/Damascus', 'Asia/Dhaka', 'Asia/Dili', 'Asia/Dubai', 'Asia/Dushanbe', 'Asia/Gaza', 'Asia/Harbin', 'Asia/Hebron', 'Asia/Ho_Chi_Minh', 'Asia/Hong_Kong', 'Asia/Hovd', 'Asia/Irkutsk', 'Asia/Istanbul', 'Asia/Jakarta', 'Asia/Jayapura', 'Asia/Jerusalem', 'Asia/Kabul', 'Asia/Kamchatka', 'Asia/Karachi', 'Asia/Kashgar', 'Asia/Kathmandu', 'Asia/Katmandu', 'Asia/Khandyga', 'Asia/Kolkata', 'Asia/Krasnoyarsk', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Kuwait', 'Asia/Macao', 'Asia/Macau', 'Asia/Magadan', 'Asia/Makassar', 'Asia/Manila', 'Asia/Muscat', 'Asia/Nicosia', 'Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Oral', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Pyongyang', 'Asia/Qatar', 'Asia/Qyzylorda', 'Asia/Rangoon', 'Asia/Riyadh', 'Asia/Saigon', 'Asia/Sakhalin', 'Asia/Samarkand', 'Asia/Seoul', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Taipei', 'Asia/Tashkent', 'Asia/Tbilisi', 'Asia/Tehran', 'Asia/Tel_Aviv', 'Asia/Thimbu', 'Asia/Thimphu', 'Asia/Tokyo', 'Asia/Ujung_Pandang', 'Asia/Ulaanbaatar', 'Asia/Ulan_Bator', 'Asia/Urumqi', 'Asia/Ust-Nera', 'Asia/Vientiane', 'Asia/Vladivostok', 'Asia/Yakutsk', 'Asia/Yekaterinburg', 'Asia/Yerevan', 'Atlantic/Azores', 'Atlantic/Bermuda', 'Atlantic/Canary', 'Atlantic/Cape_Verde', 'Atlantic/Faeroe', 'Atlantic/Faroe', 'Atlantic/Jan_Mayen', 'Atlantic/Madeira', 'Atlantic/Reykjavik', 'Atlantic/South_Georgia', 'Atlantic/St_Helena', 'Atlantic/Stanley', 'Australia/ACT', 'Australia/Adelaide', 'Australia/Brisbane', 'Australia/Broken_Hill', 'Australia/Canberra', 'Australia/Currie', 'Australia/Darwin', 'Australia/Eucla', 'Australia/Hobart', 'Australia/LHI', 'Australia/Lindeman', 'Australia/Lord_Howe', 'Australia/Melbourne', 'Australia/North', 'Australia/NSW', 'Australia/Perth', 'Australia/Queensland', 'Australia/South', 'Australia/Sydney', 'Australia/Tasmania', 'Australia/Victoria', 'Australia/West', 'Australia/Yancowinna', 'Europe/Amsterdam', 'Europe/Andorra', 'Europe/Athens', 'Europe/Belfast', 'Europe/Belgrade', 'Europe/Berlin', 'Europe/Bratislava', 'Europe/Brussels', 'Europe/Bucharest', 'Europe/Budapest', 'Europe/Busingen', 'Europe/Chisinau', 'Europe/Copenhagen', 'Europe/Dublin', 'Europe/Gibraltar', 'Europe/Guernsey', 'Europe/Helsinki', 'Europe/Isle_of_Man', 'Europe/Istanbul', 'Europe/Jersey', 'Europe/Kaliningrad', 'Europe/Kiev', 'Europe/Lisbon', 'Europe/Ljubljana', 'Europe/London', 'Europe/Luxembourg', 'Europe/Madrid', 'Europe/Malta', 'Europe/Mariehamn', 'Europe/Minsk', 'Europe/Monaco', 'Europe/Moscow', 'Europe/Nicosia', 'Europe/Oslo', 'Europe/Paris', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Riga', 'Europe/Rome', 'Europe/Samara', 'Europe/San_Marino', 'Europe/Sarajevo', 'Europe/Simferopol', 'Europe/Skopje', 'Europe/Sofia', 'Europe/Stockholm', 'Europe/Tallinn', 'Europe/Tirane', 'Europe/Tiraspol', 'Europe/Uzhgorod', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Vilnius', 'Europe/Volgograd', 'Europe/Warsaw', 'Europe/Zagreb', 'Europe/Zaporozhye', 'Europe/Zurich', 'Indian/Antananarivo', 'Indian/Chagos', 'Indian/Christmas', 'Indian/Cocos', 'Indian/Comoro', 'Indian/Kerguelen', 'Indian/Mahe', 'Indian/Maldives', 'Indian/Mauritius', 'Indian/Mayotte', 'Indian/Reunion', 'Pacific/Apia', 'Pacific/Auckland', 'Pacific/Chatham', 'Pacific/Chuuk', 'Pacific/Easter', 'Pacific/Efate', 'Pacific/Enderbury', 'Pacific/Fakaofo', 'Pacific/Fiji', 'Pacific/Funafuti', 'Pacific/Galapagos', 'Pacific/Gambier', 'Pacific/Guadalcanal', 'Pacific/Guam', 'Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Kiritimati', 'Pacific/Kosrae', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Marquesas', 'Pacific/Midway', 'Pacific/Nauru', 'Pacific/Niue', 'Pacific/Norfolk', 'Pacific/Noumea', 'Pacific/Pago_Pago', 'Pacific/Palau', 'Pacific/Pitcairn', 'Pacific/Pohnpei', 'Pacific/Ponape', 'Pacific/Port_Moresby', 'Pacific/Rarotonga', 'Pacific/Saipan', 'Pacific/Samoa', 'Pacific/Tahiti', 'Pacific/Tarawa', 'Pacific/Tongatapu', 'Pacific/Truk', 'Pacific/Wake', 'Pacific/Wallis', 'Pacific/Yap', 'Brazil/Acre', 'Brazil/DeNoronha', 'Brazil/East', 'Brazil/West', 'Canada/Atlantic', 'Canada/Central', 'Canada/East-Saskatchewan', 'Canada/Eastern', 'Canada/Mountain', 'Canada/Newfoundland', 'Canada/Pacific', 'Canada/Saskatchewan', 'Canada/Yukon', 'CET/CET', 'Chile/Continental', 'Chile/EasterIsland', 'CST6CDT/CST6CDT', 'Cuba/Cuba', 'EET/EET', 'Egypt/Egypt', 'Eire/Eire', 'EST/EST', 'EST5EDT/EST5EDT', 'Etc/GMT', 'Etc/GMT+0', 'Etc/GMT+1', 'Etc/GMT+10', 'Etc/GMT+11', 'Etc/GMT+12', 'Etc/GMT+2', 'Etc/GMT+3', 'Etc/GMT+4', 'Etc/GMT+5', 'Etc/GMT+6', 'Etc/GMT+7', 'Etc/GMT+8', 'Etc/GMT+9', 'Etc/GMT-0', 'Etc/GMT-1', 'Etc/GMT-10', 'Etc/GMT-11', 'Etc/GMT-12', 'Etc/GMT-13', 'Etc/GMT-14', 'Etc/GMT-2', 'Etc/GMT-3', 'Etc/GMT-4', 'Etc/GMT-5', 'Etc/GMT-6', 'Etc/GMT-7', 'Etc/GMT-8', 'Etc/GMT-9', 'Etc/GMT0', 'Etc/Greenwich', 'Etc/UCT', 'Etc/Universal', 'Etc/UTC', 'Etc/Zulu', 'Factory/Factory', 'GB/GB', 'GB-Eire/GB-Eire', 'GMT/GMT', 'GMT+0/GMT+0', 'GMT-0/GMT-0', 'GMT0/GMT0', 'Greenwich/Greenwich', 'Hongkong/Hongkong', 'HST/HST', 'Iceland/Iceland', 'Iran/Iran', 'Israel/Israel', 'Jamaica/Jamaica', 'Japan/Japan', 'Kwajalein/Kwajalein', 'Libya/Libya', 'MET/MET', 'Mexico/BajaNorte', 'Mexico/BajaSur', 'Mexico/General', 'MST/MST', 'MST7MDT/MST7MDT', 'Navajo/Navajo', 'NZ/NZ', 'NZ-CHAT/NZ-CHAT', 'Poland/Poland', 'Portugal/Portugal', 'PRC/PRC', 'PST8PDT/PST8PDT', 'ROC/ROC', 'ROK/ROK', 'Singapore/Singapore', 'Turkey/Turkey', 'UCT/UCT', 'Universal/Universal', 'US/Alaska', 'US/Aleutian', 'US/Arizona', 'US/Central', 'US/East-Indiana', 'US/Eastern', 'US/Hawaii', 'US/Indiana-Starke', 'US/Michigan', 'US/Mountain', 'US/Pacific', 'US/Pacific-New', 'US/Samoa', 'UTC/UTC', 'W-SU/W-SU', 'WET/WET', 'Zulu/Zulu') NOT NULL DEFAULT '',
  `commence` int(13) NOT NULL DEFAULT '0',
  `finished` int(13) NOT NULL DEFAULT '0',
  `year` int(4) NOT NULL DEFAULT '0',
  `month` int(2) NOT NULL DEFAULT '0',
  `day` int(2) NOT NULL DEFAULT '0',
  `week` int(2) NOT NULL DEFAULT '0',
  `hour` int(2) NOT NULL DEFAULT '0',
  `minute` int(2) NOT NULL DEFAULT '0',
  `seconds` int(2) NOT NULL DEFAULT '0',
  `segment-month` enum('0-3','3-6','6-9','9-12') NOT NULL DEFAULT '0-3',
  `segment-hour` enum('0-3','3-6','6-9','9-12','12-15','15-18','18-21','21-24') NOT NULL DEFAULT '0-3',
  `segment-minute` enum('0-15','15-30','30-45','45-60') NOT NULL DEFAULT '0-15',
  `day-name` enum('Sun','Sat','Mon','Tue','Wed','Thu','Fri') NOT NULL DEFAULT 'Sun',
  `stat` float(22,9) NOT NULL DEFAULT '0.000000000',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`key`,`year`,`month`,`day`,`week`,`hour`,`minute`,`segment-month`,`segment-hour`,`segment-minute`,`day-name`) USING BTREE KEY_BLOCK_SIZE=32,
  KEY `PERIODICS` (`commence`,`finished`,`mode`,`typal`,`type`,`typeid`),
  KEY `INDICATING` (`mode`,`typal`,`type`,`typeid`,`hash`(11),`key`(16)),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `images_scores` (
  `id` mediumint(48) NOT NULL AUTO_INCREMENT,
  `statistic_id` mediumint(32) NOT NULL DEFAULT '0',
  `value` enum('float','integer') NOT NULL DEFAULT '',
  `mode` enum('hourly','daily','weekly','biweekly','monthly','quarterly','yearly') NOT NULL DEFAULT '',
  `field` enum('sum','max','min','adv','std','end') NOT NULL DEFAULT '',
  `state` enum('item','key','typal','type') NOT NULL DEFAULT '',
  `typal` enum('icons','logo','photo','avatar') NOT NULL DEFAULT '',
  `type` enum('fields','images') NOT NULL DEFAULT '',
  `typeid` mediumint(15) NOT NULL DEFAULT '0',
  `timezone` enum('Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Asmera', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Timbuktu', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'America/Anguilla', 'America/Antigua', 'America/Araguaina', 'America/Argentina/Buenos_Aires', 'America/Argentina/Catamarca', 'America/Argentina/ComodRivadavia', 'America/Argentina/Cordoba', 'America/Argentina/Jujuy', 'America/Argentina/La_Rioja', 'America/Argentina/Mendoza', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Aruba', 'America/Asuncion', 'America/Atikokan', 'America/Atka', 'America/Bahia', 'America/Bahia_Banderas', 'America/Barbados', 'America/Belem', 'America/Belize', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Bogota', 'America/Boise', 'America/Buenos_Aires', 'America/Cambridge_Bay', 'America/Campo_Grande', 'America/Cancun', 'America/Caracas', 'America/Catamarca', 'America/Cayenne', 'America/Cayman', 'America/Chicago', 'America/Chihuahua', 'America/Coral_Harbour', 'America/Cordoba', 'America/Costa_Rica', 'America/Creston', 'America/Cuiaba', 'America/Curacao', 'America/Danmarkshavn', 'America/Dawson', 'America/Dawson_Creek', 'America/Denver', 'America/Detroit', 'America/Dominica', 'America/Edmonton', 'America/Eirunepe', 'America/El_Salvador', 'America/Ensenada', 'America/Fort_Wayne', 'America/Fortaleza', 'America/Glace_Bay', 'America/Godthab', 'America/Goose_Bay', 'America/Grand_Turk', 'America/Grenada', 'America/Guadeloupe', 'America/Guatemala', 'America/Guayaquil', 'America/Guyana', 'America/Halifax', 'America/Havana', 'America/Hermosillo', 'America/Indiana/Indianapolis', 'America/Indiana/Knox', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Tell_City', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Indianapolis', 'America/Inuvik', 'America/Iqaluit', 'America/Jamaica', 'America/Jujuy', 'America/Juneau', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Knox_IN', 'America/Kralendijk', 'America/La_Paz', 'America/Lima', 'America/Los_Angeles', 'America/Louisville', 'America/Lower_Princes', 'America/Maceio', 'America/Managua', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Matamoros', 'America/Mazatlan', 'America/Mendoza', 'America/Menominee', 'America/Merida', 'America/Metlakatla', 'America/Mexico_City', 'America/Miquelon', 'America/Moncton', 'America/Monterrey', 'America/Montevideo', 'America/Montreal', 'America/Montserrat', 'America/Nassau', 'America/New_York', 'America/Nipigon', 'America/Nome', 'America/Noronha', 'America/North_Dakota/Beulah', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/Ojinaga', 'America/Panama', 'America/Pangnirtung', 'America/Paramaribo', 'America/Phoenix', 'America/Port-au-Prince', 'America/Port_of_Spain', 'America/Porto_Acre', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Rainy_River', 'America/Rankin_Inlet', 'America/Recife', 'America/Regina', 'America/Resolute', 'America/Rio_Branco', 'America/Rosario', 'America/Santa_Isabel', 'America/Santarem', 'America/Santiago', 'America/Santo_Domingo', 'America/Sao_Paulo', 'America/Scoresbysund', 'America/Shiprock', 'America/Sitka', 'America/St_Barthelemy', 'America/St_Johns', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Thomas', 'America/St_Vincent', 'America/Swift_Current', 'America/Tegucigalpa', 'America/Thule', 'America/Thunder_Bay', 'America/Tijuana', 'America/Toronto', 'America/Tortola', 'America/Vancouver', 'America/Virgin', 'America/Whitehorse', 'America/Winnipeg', 'America/Yakutat', 'America/Yellowknife', 'Antarctica/Casey', 'Antarctica/Davis', 'Antarctica/DumontDUrville', 'Antarctica/Macquarie', 'Antarctica/Mawson', 'Antarctica/McMurdo', 'Antarctica/Palmer', 'Antarctica/Rothera', 'Antarctica/South_Pole', 'Antarctica/Syowa', 'Antarctica/Vostok', 'Arctic/Longyearbyen', 'Asia/Aden', 'Asia/Almaty', 'Asia/Amman', 'Asia/Anadyr', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Ashkhabad', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Baku', 'Asia/Bangkok', 'Asia/Beirut', 'Asia/Bishkek', 'Asia/Brunei', 'Asia/Calcutta', 'Asia/Choibalsan', 'Asia/Chongqing', 'Asia/Chungking', 'Asia/Colombo', 'Asia/Dacca', 'Asia/Damascus', 'Asia/Dhaka', 'Asia/Dili', 'Asia/Dubai', 'Asia/Dushanbe', 'Asia/Gaza', 'Asia/Harbin', 'Asia/Hebron', 'Asia/Ho_Chi_Minh', 'Asia/Hong_Kong', 'Asia/Hovd', 'Asia/Irkutsk', 'Asia/Istanbul', 'Asia/Jakarta', 'Asia/Jayapura', 'Asia/Jerusalem', 'Asia/Kabul', 'Asia/Kamchatka', 'Asia/Karachi', 'Asia/Kashgar', 'Asia/Kathmandu', 'Asia/Katmandu', 'Asia/Khandyga', 'Asia/Kolkata', 'Asia/Krasnoyarsk', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Kuwait', 'Asia/Macao', 'Asia/Macau', 'Asia/Magadan', 'Asia/Makassar', 'Asia/Manila', 'Asia/Muscat', 'Asia/Nicosia', 'Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Oral', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Pyongyang', 'Asia/Qatar', 'Asia/Qyzylorda', 'Asia/Rangoon', 'Asia/Riyadh', 'Asia/Saigon', 'Asia/Sakhalin', 'Asia/Samarkand', 'Asia/Seoul', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Taipei', 'Asia/Tashkent', 'Asia/Tbilisi', 'Asia/Tehran', 'Asia/Tel_Aviv', 'Asia/Thimbu', 'Asia/Thimphu', 'Asia/Tokyo', 'Asia/Ujung_Pandang', 'Asia/Ulaanbaatar', 'Asia/Ulan_Bator', 'Asia/Urumqi', 'Asia/Ust-Nera', 'Asia/Vientiane', 'Asia/Vladivostok', 'Asia/Yakutsk', 'Asia/Yekaterinburg', 'Asia/Yerevan', 'Atlantic/Azores', 'Atlantic/Bermuda', 'Atlantic/Canary', 'Atlantic/Cape_Verde', 'Atlantic/Faeroe', 'Atlantic/Faroe', 'Atlantic/Jan_Mayen', 'Atlantic/Madeira', 'Atlantic/Reykjavik', 'Atlantic/South_Georgia', 'Atlantic/St_Helena', 'Atlantic/Stanley', 'Australia/ACT', 'Australia/Adelaide', 'Australia/Brisbane', 'Australia/Broken_Hill', 'Australia/Canberra', 'Australia/Currie', 'Australia/Darwin', 'Australia/Eucla', 'Australia/Hobart', 'Australia/LHI', 'Australia/Lindeman', 'Australia/Lord_Howe', 'Australia/Melbourne', 'Australia/North', 'Australia/NSW', 'Australia/Perth', 'Australia/Queensland', 'Australia/South', 'Australia/Sydney', 'Australia/Tasmania', 'Australia/Victoria', 'Australia/West', 'Australia/Yancowinna', 'Europe/Amsterdam', 'Europe/Andorra', 'Europe/Athens', 'Europe/Belfast', 'Europe/Belgrade', 'Europe/Berlin', 'Europe/Bratislava', 'Europe/Brussels', 'Europe/Bucharest', 'Europe/Budapest', 'Europe/Busingen', 'Europe/Chisinau', 'Europe/Copenhagen', 'Europe/Dublin', 'Europe/Gibraltar', 'Europe/Guernsey', 'Europe/Helsinki', 'Europe/Isle_of_Man', 'Europe/Istanbul', 'Europe/Jersey', 'Europe/Kaliningrad', 'Europe/Kiev', 'Europe/Lisbon', 'Europe/Ljubljana', 'Europe/London', 'Europe/Luxembourg', 'Europe/Madrid', 'Europe/Malta', 'Europe/Mariehamn', 'Europe/Minsk', 'Europe/Monaco', 'Europe/Moscow', 'Europe/Nicosia', 'Europe/Oslo', 'Europe/Paris', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Riga', 'Europe/Rome', 'Europe/Samara', 'Europe/San_Marino', 'Europe/Sarajevo', 'Europe/Simferopol', 'Europe/Skopje', 'Europe/Sofia', 'Europe/Stockholm', 'Europe/Tallinn', 'Europe/Tirane', 'Europe/Tiraspol', 'Europe/Uzhgorod', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Vilnius', 'Europe/Volgograd', 'Europe/Warsaw', 'Europe/Zagreb', 'Europe/Zaporozhye', 'Europe/Zurich', 'Indian/Antananarivo', 'Indian/Chagos', 'Indian/Christmas', 'Indian/Cocos', 'Indian/Comoro', 'Indian/Kerguelen', 'Indian/Mahe', 'Indian/Maldives', 'Indian/Mauritius', 'Indian/Mayotte', 'Indian/Reunion', 'Pacific/Apia', 'Pacific/Auckland', 'Pacific/Chatham', 'Pacific/Chuuk', 'Pacific/Easter', 'Pacific/Efate', 'Pacific/Enderbury', 'Pacific/Fakaofo', 'Pacific/Fiji', 'Pacific/Funafuti', 'Pacific/Galapagos', 'Pacific/Gambier', 'Pacific/Guadalcanal', 'Pacific/Guam', 'Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Kiritimati', 'Pacific/Kosrae', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Marquesas', 'Pacific/Midway', 'Pacific/Nauru', 'Pacific/Niue', 'Pacific/Norfolk', 'Pacific/Noumea', 'Pacific/Pago_Pago', 'Pacific/Palau', 'Pacific/Pitcairn', 'Pacific/Pohnpei', 'Pacific/Ponape', 'Pacific/Port_Moresby', 'Pacific/Rarotonga', 'Pacific/Saipan', 'Pacific/Samoa', 'Pacific/Tahiti', 'Pacific/Tarawa', 'Pacific/Tongatapu', 'Pacific/Truk', 'Pacific/Wake', 'Pacific/Wallis', 'Pacific/Yap', 'Brazil/Acre', 'Brazil/DeNoronha', 'Brazil/East', 'Brazil/West', 'Canada/Atlantic', 'Canada/Central', 'Canada/East-Saskatchewan', 'Canada/Eastern', 'Canada/Mountain', 'Canada/Newfoundland', 'Canada/Pacific', 'Canada/Saskatchewan', 'Canada/Yukon', 'CET/CET', 'Chile/Continental', 'Chile/EasterIsland', 'CST6CDT/CST6CDT', 'Cuba/Cuba', 'EET/EET', 'Egypt/Egypt', 'Eire/Eire', 'EST/EST', 'EST5EDT/EST5EDT', 'Etc/GMT', 'Etc/GMT+0', 'Etc/GMT+1', 'Etc/GMT+10', 'Etc/GMT+11', 'Etc/GMT+12', 'Etc/GMT+2', 'Etc/GMT+3', 'Etc/GMT+4', 'Etc/GMT+5', 'Etc/GMT+6', 'Etc/GMT+7', 'Etc/GMT+8', 'Etc/GMT+9', 'Etc/GMT-0', 'Etc/GMT-1', 'Etc/GMT-10', 'Etc/GMT-11', 'Etc/GMT-12', 'Etc/GMT-13', 'Etc/GMT-14', 'Etc/GMT-2', 'Etc/GMT-3', 'Etc/GMT-4', 'Etc/GMT-5', 'Etc/GMT-6', 'Etc/GMT-7', 'Etc/GMT-8', 'Etc/GMT-9', 'Etc/GMT0', 'Etc/Greenwich', 'Etc/UCT', 'Etc/Universal', 'Etc/UTC', 'Etc/Zulu', 'Factory/Factory', 'GB/GB', 'GB-Eire/GB-Eire', 'GMT/GMT', 'GMT+0/GMT+0', 'GMT-0/GMT-0', 'GMT0/GMT0', 'Greenwich/Greenwich', 'Hongkong/Hongkong', 'HST/HST', 'Iceland/Iceland', 'Iran/Iran', 'Israel/Israel', 'Jamaica/Jamaica', 'Japan/Japan', 'Kwajalein/Kwajalein', 'Libya/Libya', 'MET/MET', 'Mexico/BajaNorte', 'Mexico/BajaSur', 'Mexico/General', 'MST/MST', 'MST7MDT/MST7MDT', 'Navajo/Navajo', 'NZ/NZ', 'NZ-CHAT/NZ-CHAT', 'Poland/Poland', 'Portugal/Portugal', 'PRC/PRC', 'PST8PDT/PST8PDT', 'ROC/ROC', 'ROK/ROK', 'Singapore/Singapore', 'Turkey/Turkey', 'UCT/UCT', 'Universal/Universal', 'US/Alaska', 'US/Aleutian', 'US/Arizona', 'US/Central', 'US/East-Indiana', 'US/Eastern', 'US/Hawaii', 'US/Indiana-Starke', 'US/Michigan', 'US/Mountain', 'US/Pacific', 'US/Pacific-New', 'US/Samoa', 'UTC/UTC', 'W-SU/W-SU', 'WET/WET', 'Zulu/Zulu') NOT NULL DEFAULT '',
  `written` int(13) NOT NULL DEFAULT '0',
  `float` float(22,9) NOT NULL DEFAULT '0.000000000',
  `integer` int(13) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `PERIODICS` (`value`,`field`,`mode`,`typal`,`type`,`typeid`),
  KEY `INDICATING` (`mode`,`typal`,`type`,`typeid`,`statistic_id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
